// Gemini API Client

/**
 * Sends a prompt to the Gemini API and returns the parsed JSON response.
 * @param {string} text - The input text (either full page or selected word).
 * @param {string} promptType - 'page_analysis' or 'word_lookup'.
 * @param {string} apiKey - The Gemini API Key.
 * @returns {Promise<any>}
 */
export async function analyzeText(text, promptType, apiKey, modelName = 'gemini-2.5-flash-lite') {
  if (!apiKey) {
    throw new Error('Gemini API key is not configured. Please add it in the settings.');
  }

  // Load the prompt template from the extension assets
  const promptFile = promptType === 'page_analysis' ? 'prompts/page_analysis.txt' : 'prompts/word_lookup.txt';
  const responseText = await fetch(chrome.runtime.getURL(promptFile));
  if (!responseText.ok) {
    throw new Error(`Failed to load prompt template: ${promptFile}`);
  }
  const template = await responseText.text();
  const prompt = template.replace('{{TEXT}}', text);

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;

  const requestBody = {
    contents: [
      {
        parts: [
          {
            text: prompt
          }
        ]
      }
    ],
    generationConfig: {
      responseMimeType: "application/json",
      temperature: 0.2
    }
  };

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(requestBody)
  });

  if (!response.ok) {
    const errorText = await response.text();
    console.error('Gemini API error response:', errorText);
    throw new Error(`Gemini API error: ${response.status} ${response.statusText}`);
  }

  const result = await response.json();
  
  if (!result.candidates || result.candidates.length === 0) {
    throw new Error('No response generated by Gemini.');
  }

  const generatedText = result.candidates[0].content.parts[0].text;
  
  try {
    const parsedData = JSON.parse(generatedText);
    return parsedData;
  } catch (e) {
    console.error('Failed to parse Gemini response as JSON. Raw response:', generatedText);
    throw new Error('Gemini did not return valid JSON. Please try again.');
  }
}
